name: Test for Liquidsoap Script
description: Tests for Liquidsoap scripts

inputs:
  scripts:
    description: "Scripts to be tested"
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: /main.sh
  args: 
   - ${{ inputs.scripts }}
